name: Deployment
on: push

jobs:
  pre-config:
    name: Deploy to Linode
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH to Linode Server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.NANODE_USER }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: echo "Hey"
