name: Deployment
on: push

jobs:
  pre-config:
    name: Deploy to Linode
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH to Linode
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.NANODE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }
        port: 22
        script: whoami
