name: Deployment
on: push

jobs:
  pre-config:
    name: Deploy to Linode
    runs-on: ubuntu-latest

    steps:
    - name: Begin Configuration
      run: echo "Beginning configuration..."

    - name: Clone repo
      uses: actions/checkout@v3      

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        update-pip: "false"
        path: "requirements.txt"

    - name: Set Env variables
      run: |
        export CONN_STR=${{ secrets.CONN_STR }}
        export MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
        export MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
        export LOCAL_APP_SCRT=${{ secrets.LOCAL_APP_SCRT }}
        export AFRICASTALKING_USERNAME=${{ secrets.AFRICASTALKING_USERNAME }}
        export AFRICASTALKING_API_KEY=${{ secrets.AFRICASTALKING_API_KEY }}
        export L_RECAPTCHA_PUBLIC_KEY=${{ secrets.L_RECAPTCHA_PUBLIC_KEY }}
        export L_RECAPTCHA_PRIVATE_KEY=${{ secrets.L_RECAPTCHA_PRIVATE_KEY }}
        export GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
        export GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
        export MOBILE=${{ secrets.MOBILE }}
        export EMAIL=${{ secrets.EMAIL }}
        export LOCATION=${{ secrets.LOCATION }}
        echo "xxxxxxxx"
        echo $L_RECAPTCHA_PRIVATE_KEY
      shell: bash
  
    - name: SSH to Linode
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.NANODE_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd savannah_online_services
          source env/bin/activate
          git add .
          git commit "pycached changes"
          git pull
