name: Deployment
on: push

jobs:
  pre-config:
    name: Deploy to Linode
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH to Linode
      uses: fifsky/ssh-action@master
      with:
        command: |
          ls -a
        host: ${{ secrets.HOST }}
        user: ${{ secrets.NANODE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
