name: Deployment
on: push

jobs:
  pre-config:
    name: Deploy to Linode
    runs-on: ubuntu-latest

    steps:
    - name: Begin Configuration
      run: echo "Beginning configuration..."

    - name: Clone repo
      uses: actions/checkout@v3      

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        update-pip: "false"
        path: "requirements.txt"
  
    - name: SSH to Linode
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.NANODE_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd savannah_online_services
          source env/bin/activate
          git add .
          git commit "pycached changes"
          git pull
