name: Setup
on: push

jobs:
  pre-config:
     runs-on: ubuntu-latest

     steps:
     - name: Begin Configuration
       run: echo "Beginning configuration..."

     - name: Setup Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'

     - name: Install Dependencies
       run: pip install -r requirements.txt
       
     - name: Run Tests
       run: ./run_tests.sh
       shell: bash